---
abstract: 'Binary Search a sorted array with XS routines.'
author:
  - 'David Oswald <davido [@at] cpan [d.o.t.] org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '6.62'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: List-BinarySearch-XS
no_index:
  directory:
    - t
    - inc
provides:
  List::BinarySearch::XS:
    file: lib/List/BinarySearch/XS.pm
    version: '0.08'
requires:
  perl: '5.008000'
resources:
  bugtracker: https://github.com/daoswald/List-BinarySearch-XS/issues
  repository: https://github.com/daoswald/List-BinarySearch-XS.git
version: '0.08'
